using CommunityToolkit.Mvvm.ComponentModel;

namespace VenueOps.ViewModels;

/// <summary>
/// Base class for all ViewModels.
/// Inherits ObservableObject (CommunityToolkit.Mvvm) which provides
/// INotifyPropertyChanged, INotifyPropertyChanging, and SetProperty helpers.
///
/// Uses the CommunityToolkit.Mvvm 8.3+ partial-property syntax (C# 13).
/// [ObservableProperty] is placed on the property declaration rather than
/// on a backing field — the source generator completes the implementation.
///
/// The OnBusyStateChanged virtual hook lets derived VMs notify their own
/// commands when IsBusy flips, without coupling BaseViewModel to specific
/// command names.
/// </summary>
public abstract partial class BaseViewModel : ObservableObject
{
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsNotBusy))]
    public partial bool IsBusy { get; set; }

    [ObservableProperty]
    public partial string Title { get; set; } = string.Empty;

    public bool IsNotBusy => !IsBusy;

    // Partial hook generated by the source generator — called every time
    // IsBusy changes. Bridges to the virtual method below.
    partial void OnIsBusyChanged(bool value) => OnBusyStateChanged(value);

    /// <summary>
    /// Override in derived ViewModels to call command.NotifyCanExecuteChanged()
    /// for any commands whose CanExecute depends on IsBusy.
    /// </summary>
    protected virtual void OnBusyStateChanged(bool isBusy) { }
}
